# Exclude ECC.
URAM_WIDTH_BITS = 64
URAM_WIDTH_BYTES = URAM_WIDTH_BITS // 8
URAM_DEPTH = 4096

BRAM_WIDTH_BITS = 64
BRAM_WIDTH_BYTES = BRAM_WIDTH_BITS // 8
BRAM_DEPTH_WIDE_COEFFICIENT = 512
BRAM_DEPTH_NARROW_COEFFICIENT = 1024

NUM_DSPS_WIDE_COEFFICIENT = 32
NUM_DSPS_NARROW_COEFFICIENT = 11

MAX_SRAM_SIZE_BYTES = 38 * 1024 * 1024

POLYNOMIALS_PER_CIPHERTEXT = 2
